[package]
name = "tera-actix-template"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.5"
actix-web = "4.5.1"
env_logger = "0.11.3"
lazy_static = "1.4.0"
log = "0.4.21"
rand = "0.8.5"
serde = "1.0.202"
tera = "1.19.1"
